### PR TITLE
Ticket917

### PR DESCRIPTION
**Pull request by FreddieAkeroyd**
See ISISComputingGroup/IBEX#917

### CODE REVIEW

**Comment by FreddieAkeroyd** [comment]
Sorry - wrong base for merge...

**Comment by ralphlange** [comment]
You're too fast! :-)
I'm on it - and will tag a new release. (Needed for a new Gateway release.)

**Comment by ralphlange** [comment]
See #4 ... committed / closed in 3252364.

**Comment by FreddieAkeroyd** [comment]
Thanks @ralphlange

**Pull request closed without merging**
